sudo: required
dist: trusty
language: go

go:
  - 1.6
  - tip

python:
  - "3.4"

install:
  - uname -a
  - lsb_release -a
  - sudo apt-get update
  - sudo apt-get -y install python3-pip drbd8-utils
  - python3 -V
  - pip3 -V
  - sudo pip3 install git+https://github.com/g2p/vido.git@for-travis
  - curl -LO https://media.githubusercontent.com/media/naota/kernel/master/uml-4.1.19/linux-4.1.19.xz
  - unxz linux-4.1.19.xz
  - chmod u+x linux-4.1.19

script:
  - ls -l
  - vido --pass-env GOROOT GOTOOLDIR GO15VENDOREXPERIMENT --kernel ./linux-4.1.19 -- bash .travis-test.sh
