language: go

go:
  - 1.6
  - tip

python:
  - "3.3"

install:
  - uname -a
  - lsb_release -a
  - sudo apt-get update
  - sudo apt-get install python3
  - which python3
  - pip3 install git+https://github.com/g2p/vido.git@for-travis
  - curl -LO https://media.githubusercontent.com/media/naota/kernel/master/uml-4.1.19/linux-4.1.19.xz
  - unxz linux-4.1.19.xz
  - chmod u+x linux-4.1.19

script:
  - vido --kernel linux-4.1.19 -- bash .travis-test.sh
